// <auto-generated />
using System;
using KreditzBankData.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KreditzBankData.Shared.Data.Migrations
{
    [DbContext(typeof(KreditzBankDataDbContext))]
    [Migration("20260303183313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_account_account_number");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.AccountHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_holders_account_id");

                    b.ToTable("account_holders", (string)null);
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_balances_batch_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_balances_account_id_created_at");

                    b.ToTable("balances", (string)null);
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_categories_is_active");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RecordsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_ingestion_logs_batch_id");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("ix_ingestion_logs_file_hash");

                    b.ToTable("ingestion_logs", (string)null);
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("AnomalyReasons")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAnomaly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_transactions_batch_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("IsAnomaly")
                        .HasDatabaseName("ix_transactions_is_anomaly");

                    b.HasIndex("AccountId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_account_id_external_id");

                    b.HasIndex("AccountId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_account_id_transaction_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.AccountHolder", b =>
                {
                    b.HasOne("KreditzBankData.Shared.Data.Entities.Account", "Account")
                        .WithMany("Holders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Balance", b =>
                {
                    b.HasOne("KreditzBankData.Shared.Data.Entities.Account", "Account")
                        .WithMany("Balances")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KreditzBankData.Shared.Data.Entities.IngestionLog", "IngestionLog")
                        .WithMany("Balances")
                        .HasForeignKey("BatchId")
                        .HasPrincipalKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("IngestionLog");
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Transaction", b =>
                {
                    b.HasOne("KreditzBankData.Shared.Data.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KreditzBankData.Shared.Data.Entities.IngestionLog", "IngestionLog")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .HasPrincipalKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KreditzBankData.Shared.Data.Entities.Categories", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("IngestionLog");
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Account", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Holders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.Categories", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KreditzBankData.Shared.Data.Entities.IngestionLog", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
